name: tutorial_3
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: Erik <email@example.com>

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
  angular: ^5.0.0-beta
  angular_components: ^0.9.0-beta
  angular_router: ^2.0.0-alpha


dev_dependencies:
  build_runner: ^0.9.1
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  build_config: ^0.3.1


